version: '3'
services:
  server:
    build: ./server
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    container_name: fabric-server
    restart: always
    volumes:
      - ./server/:/app
    depends_on:
      - database
  database:
    image: postgres:11.6-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    container_name: fabric-database
    restart: always
